// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2813.TshirtLauncher.subsystems;

import org.usfirst.frc2813.TshirtLauncher.RobotMap;

import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class ShirtLauncher extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid solenoid = RobotMap.solenoid;
	Relay shootLeft = RobotMap.leftRelay;
	Relay shootRight = RobotMap.rightRelay;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	// Control by Pheumatic Control Module - 2015
	/*
	 * public void pcmlaunchshirt(){ shootair.set(Solenoid.Value.kForward); }
	 */

	// Control by Spike Relay 0
	public void shootLeft() {
		shootLeft.set(Relay.Value.kForward);
		System.out.println("shootLeft-kForward");
	}

	public void retractLeft() {
		shootLeft.set(Relay.Value.kOff);
		System.out.println("retractLeft-Reverse");
	}

	// Control by Spike Relay 1
	public void shootRight() {
		shootRight.set(Relay.Value.kForward);
		System.out.println("shootRight-kForward");
	}

	public void retractRight() {
		shootRight.set(Relay.Value.kOff);
		System.out.println("retractRight-Reverse");
	}

	public void toggleSolenoid() {
		shootRight.set(Relay.Value.kOff);
		System.out.println("solenoid-Toggle");
	}

	public void solenoidOn() {
		shootRight.set(Relay.Value.kOff);
		System.out.println("solenoid-On");
	}

	public void solenoidOff() {
		shootRight.set(Relay.Value.kOff);
		System.out.println("solenoid-Off");
	}

}
