// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.TshirtLauncher;
    
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController chassisleftFront;
    public static SpeedController chassisleftBack;
    public static SpeedController chassisrightFront;
    public static SpeedController chassisrightBack;
    public static RobotDrive chassisDrivetrain;
    public static Solenoid solenoid;
    public static Relay leftRelay;
    public static Relay rightRelay;
    
    //public static Relay spikeLauncherShootairRev;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisleftFront = new Talon(5);
        LiveWindow.addActuator("Chassis", "leftFront", (Talon) chassisleftFront);
        
        chassisleftBack = new Talon(4);
        LiveWindow.addActuator("Chassis", "leftBack", (Talon) chassisleftBack);
        
        chassisrightFront = new Talon(2);
        LiveWindow.addActuator("Chassis", "rightFront", (Talon) chassisrightFront);
        
        chassisrightBack = new Talon(3);
        LiveWindow.addActuator("Chassis", "rightBack", (Talon) chassisrightBack);
        
        chassisDrivetrain = new RobotDrive(chassisleftFront, chassisleftBack,
              chassisrightFront, chassisrightBack);
        
        chassisDrivetrain.setSafetyEnabled(true);
        chassisDrivetrain.setExpiration(0.1);
        chassisDrivetrain.setSensitivity(0.5);
        chassisDrivetrain.setMaxOutput(1.0);
        
        //chassisDrivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        //chassisDrivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);

        //Warning, the two modules in robot builder are different!
        solenoid = new Solenoid(0);
        LiveWindow.addActuator("ShirtLauncher", "ReleaseAir", solenoid);
        
        leftRelay = new Relay(0);
        LiveWindow.addActuator("ShirtLauncher", "LeftRelay", leftRelay);
        
        rightRelay = new Relay(1);
        LiveWindow.addActuator("ShirtLauncher", "RightRelay", rightRelay);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
